openapi: 3.0.3
info:
  title: HTTP responses description
  description: HTTP Responses description
  version: 1.0.0

paths: { }

components:
  responses:
    '200':
      description: Success

    '204':
      description: No Content

    '400':
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    '401':
      description: Authorization error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: Access forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '502':
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: Service Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      properties:
        code:
          type: string
          example: 'BadRequest'
        message:
          type: string
          example: Invalid request.
      required:
        - code
        - message
      type: object

